@startuml

class Border {
  // Atributos si los hubiera
}

class ObjetoMovil {
  + ObjetoMovil(bordesTablero: Border, elem: Element, vel: number)
}

class Pelota {
  + Pelota(bordesTablero: Border, elem: Element, vel: number, dirX: number, dirY: number, arrastre: number)
  + Mover()
  + ComprobarRebote()
  + RebotarX(inerciaY: number)    
  + RebotarY()
  + ComprobarGol()
  + Resetear(vel: number, x: number, y: number, dirX: number, dirY: number)
}

class Pala {
  + Pala(bordesTablero: Border, elem: Element, vel: number, rozamiento: number, keyCodeArriba: string, keyCodeAbajo: string)
  + IniciarMovimiento(evento: Event)
  + FinalizarMovimiento(evento: Event)
  + Mover()                                
  + Frenar()
  + ComprobarColision(bordes2: Border): boolean
}

class Marcador {
  + Marcador(elem: Element)
  + GanarPunto()
}

ObjetoMovil <|-- Pelota
ObjetoMovil <|-- Pala
Pala -- Pelota

Marcador "1" o-- "1" Element : elem
Border --* ObjetoMovil

@enduml
